apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: <APPLICATION_NAME>-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: indent
    kind: ClusterSecretStore
  target:
    name: <APPLICATION_NAME>-secret
    creationPolicy: Owner
  dataFrom:
    - key: <AWS SECRETS MANAGER NAME FOR PROD>
