name: CD
on:
  push:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  # Build an image and push it to ECR.
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and push it to ECR
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG src/
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image-tag::$IMAGE_TAG"

      - name: Get current branch name
        id: extract-branch
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - name: Map branch name
        id: map-branch
        run: |
          if [[ ${{steps.extract-branch.outputs.branch}} == 'main' ]]; then
              echo "::set-output name=environment::prod"
          else
              echo "::set-output name=environment::dev"
          fi

      - name: Kustomize Kubernetes resources
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ steps.build-image.outputs.image-tag }}
        run: |
          cd infra/k8s/environments/${{steps.map-branch.outputs.environment}}
          echo "Set new image tag: ${{steps.build-image.outputs.image-tag}}"
          kustomize edit set image IMAGE-PLACEHOLDER=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          cat kustomization.yml

      - name: Archive K8s resources
        uses: actions/upload-artifact@v2
        with:
          name: k8s
          path: infra/k8s

      - name: Set target branch name
        id: set-target-branch
        run: |
          case ${{steps.extract-branch.outputs.branch}} in
              main|master)
                  echo "::set-output name=branch::main"
                  ;;
              *)
                  echo "::set-output name=branch::develop"
                  ;;
          esac

      - name: Dispatch repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CD_ACCESS_TOKEN }}
          repository: ${{ secrets.INFRA_REPO }}
          event-type: image-created
          client-payload: '{"branch": "${{ steps.set-target-branch.outputs.branch }}", "run_id": "${{ github.run_id }}"}'
