name: CD
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  # Build an image and push it to ECR.
  build:
    runs-on: ubuntu-20.04

    outputs:
      image-tag: ${{ steps.build-image.outputs.image-tag }}

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and push it to ECR
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG src/
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          # echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "::set-output name=ecr-registry::$ECR_REGISTRY"
          echo "::set-output name=image-tag::$IMAGE_TAG"

  # Kustomize resources and commit.
  deploy:
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Checkout infrastructure repository
        uses: actions/checkout@v2
        with:
          repository: <USER>/<REPOSITORY_NAME>
          ref: develop
          token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
          path: infra

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update Kubernetes resources
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ needs.build.outputs.image-tag }}
        run: |
          cd infra/k8s/environments/dev
          echo "Set new image ${{needs.build.outputs.image}}"
          kustomize edit set image <KUSTOMIZE IMAGE NAME>=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          cat kustomization.yml

      - name: Commit kustomized YAMLs
        run: |
          cd infra
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "Update image tag"
          git push -u origin develop